
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
source $VIMRUNTIME/../vimfiles/archlinux.vim

source ~/.vim/bepo.vim

filetype plugin on

set mouse=a
set ttymouse=sgr
set cursorline

" line numbers
set number
set relativenumber

" folding
set foldenable
set foldmethod=indent
set foldlevel=99

" cursor 'margin' with top and bottom
set scrolloff=10

" auto utf-8
set encoding=utf-8
set fileencoding=utf-8

" tab to spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Shift-à toggles between tabs and spaces
noremap <M-à> :set invexpandtab<CR>
noremap à :set invlist<CR>
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<,nbsp:!,space:·

" save with Ctrl-S
noremap <C-s> :w<CR>

" custom gf command: creates file if it doesn't exist
noremap gf :e <cfile><cr>

" python PEP8
augroup python_pep8
    au Filetype python
		\ setlocal tabstop=4
		\ | setlocal softtabstop=4
		\ | setlocal shiftwidth=4
		\ | setlocal textwidth=79
		\ | setlocal expandtab
		\ | setlocal autoindent
		\ | setlocal fileformat=unix
augroup end

augroup toml
    au Filetype toml
		\ setlocal tabstop=2
		\ | setlocal softtabstop=2
		\ | setlocal shiftwidth=2
		\ | setlocal expandtab
		\ | setlocal autoindent
		\ | setlocal fileformat=unix
augroup end

" plugin ultisnips
" let g:UltiSnipsSnippetDirectories=["UltiSnips"]
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
" call UltiSnips#RefreshSnippets()

" plugin vimtex
let g:tex_flavor='latex'
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_method = 'latexmk'
let maplocalleader = ","
